BANGTANS/BANGTANS/Models/MemberViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BANGTANS.Models
{
    public class MemberViewModel
    {
        public int Id { get; set; }

        // 예명
        [Display(Name = "예명")]
        public string StageName { get; set; }

        // 본명
        [Required]
        [Display(Name = "본명")]
        public string Name { get; set; }

        // 역할
        [Required]
        [Display(Name = "역할")]
        public string Role { get; set; }

        // 앨범 이미지 URL
        [Required]
        [DataType(DataType.Upload)]
        [Display(Name = "멤버이미지")]
        public string ImageUrl { get; set; }

        // 생년월일
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "생년월일")]
        //[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime BirtyDay { get; set; }

        // 키
        [Display(Name = "키")]
        public int Height { get; set; }

        // 몸무게
        [Display(Name = "몸무게")]
        public int Weight { get; set; }

        // 아티스트(그룹)아이디
        [Display(Name = "소속")]
        public int ArtistId  { get; set; }

        // 아티스트(그룹)정보
        public virtual ArtistViewModel Artist { get; set; }
    }
}

BANGTANS/BANGTANS/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BANGTANS.Models;
using System.IO;

namespace BANGTANS.Controllers
{
    public class MemberController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Member/
        // GET: Member/Index/1
        public ActionResult Index(int? id)
        {
            var memberViewModels = db.MemberViewModels.Include(m => m.Artist);
            if (id != null) {
                memberViewModels = memberViewModels.Where(a => a.ArtistId == id);
            }
            if (memberViewModels == null)
            {
                return HttpNotFound();
            }

            return View(memberViewModels.OrderByDescending(m => m.Id).ToList());
        }


        // GET: Member/GetList/1
        public ActionResult GetList(int id)
        {
            var memberViewModels = db.MemberViewModels.Where(a => a.ArtistId == id).Include(a => a.Artist);
            if(memberViewModels == null)
            {
                return HttpNotFound();
            }
            return PartialView("_MemberList", memberViewModels.ToList());
        }

        // GET: Member/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MemberViewModel memberViewModel = db.MemberViewModels.Find(id);
            if (memberViewModel == null)
            {
                return HttpNotFound();
            }
            return View(memberViewModel);
        }

        // GET: Member/Create
        public ActionResult Create()
        {
            ViewBag.ArtistId = new SelectList(db.ArtistViewModels, "Id", "Name");
            return View();
        }

        // POST: Member/Create
        // 초과 게시 공격으로부터 보호하려면 바인딩하려는 특정 속성을 사용하도록 설정하십시오. 
        // 자세한 내용은 http://go.microsoft.com/fwlink/?LinkId=317598을(를) 참조하십시오.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,StageName,Name,Role,BirtyDay,Height,Weight,ArtistId,ImageUrl")] MemberViewModel memberViewModel, HttpPostedFileBase file)
        {
            bool isSavedFile = SaveAsFile(file);
            if (isSavedFile)
            {
                memberViewModel.ImageUrl = "~/Content/Images/Member/" + file.FileName;
                if (ModelState.IsValid)
                {
                    db.MemberViewModels.Add(memberViewModel);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.ArtistId = new SelectList(db.ArtistViewModels, "Id", "Name", memberViewModel.ArtistId);
            return View(memberViewModel);
        }

        private bool SaveAsFile(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0 && IsValidExtension(file))
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/Images/Member/"), fileName);
                file.SaveAs(path);
                return true;
            }

            return false;
        }

        private Boolean IsValidExtension(HttpPostedFileBase file)
        {
            return Path.GetExtension(file.FileName).ToLower() == ".jpg"
                || Path.GetExtension(file.FileName).ToLower() == ".png"
                || Path.GetExtension(file.FileName).ToLower() == ".gif"
                || Path.GetExtension(file.FileName).ToLower() == ".jpeg";
        }

        // GET: Member/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MemberViewModel memberViewModel = db.MemberViewModels.Find(id);
            if (memberViewModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArtistId = new SelectList(db.ArtistViewModels, "Id", "Name", memberViewModel.ArtistId);
            return View(memberViewModel);
        }

        // POST: Member/Edit/5
        // 초과 게시 공격으로부터 보호하려면 바인딩하려는 특정 속성을 사용하도록 설정하십시오. 
        // 자세한 내용은 http://go.microsoft.com/fwlink/?LinkId=317598을(를) 참조하십시오.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StageName,Name,Role,BirtyDay,Height,Weight,ArtistId,ImageUrl")] MemberViewModel memberViewModel, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                bool isFileChanged = SaveAsFile(file);

                db.Entry(memberViewModel).State = EntityState.Modified;
                if (isFileChanged) memberViewModel.ImageUrl = "~/Content/Images/Member/" + file.FileName;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArtistId = new SelectList(db.ArtistViewModels, "Id", "Name", memberViewModel.ArtistId);
            return View(memberViewModel);
        }

        // GET: Member/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MemberViewModel memberViewModel = db.MemberViewModels.Find(id);
            if (memberViewModel == null)
            {
                return HttpNotFound();
            }
            return View(memberViewModel);
        }

        // POST: Member/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MemberViewModel memberViewModel = db.MemberViewModels.Find(id);
            db.MemberViewModels.Remove(memberViewModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BANGTANS/BANGTANS/Views/Member/Create.cshtml
@model BANGTANS.Models.MemberViewModel

@{
    ViewBag.Title = "Create";
}

<h2>멤버 등록</h2>


@using (Html.BeginForm("Create", "Member", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>신규 멤버 정보</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StageName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StageName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StageName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 filebox preview-image">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control upload-name", @readonly = "true", @Id = "ImageUrl", @style = "max-width: 210px; margin-bottom: .25em;" } })
                <label for="file">업로드</label>
                <input type="file" name="file" id="file" class="upload-hidden" />
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirtyDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirtyDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirtyDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistId, "ArtistId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ArtistId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArtistId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" disabled="disabled" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "", htmlAttributes: new { @class = "btn btn-default btn-xs" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>
        $(document).ready(function () {
            var fileTarget = $('.filebox .upload-hidden');

            fileTarget.on('change', function () {
                if (window.FileReader) {
                    var filename = $(this)[0].files[0].name;
                } else {
                    var filename = $(this).val().split('/').pop().split('\\').pop();
                }

                //$(this).siblings('.upload-name').val(filename);
                $("input#ImageUrl").val(filename);
            });
        });
</script>

}

BANGTANS/BANGTANS/Views/Member/Delete.cshtml
@model BANGTANS.Models.MemberViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>정보 삭제</h2>

<h3>멤버 정보</h3>
<div>
    <h4>(삭제한 멤버 정보는 복구할 수 없으니, 확인 후 삭제하세요.)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artist.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirtyDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirtyDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Back to List", "Index", "", htmlAttributes: new { @class = "btn btn-default btn-xs" })
            <span>&nbsp;&nbsp;&nbsp;</span>
            <input type="submit" value="Delete" class="btn btn-primary" disabled="disabled" />
        </div>
    }
</div>

BANGTANS/BANGTANS/Views/Member/Details.cshtml
@model BANGTANS.Models.MemberViewModel

@{
    ViewBag.Title = "Details";
}

<h2>상세정보</h2>

<div>
    <div class="category-title" style="text-align:center;">
        <h4>@Html.DisplayFor(model => model.StageName)</h4>
        <hr class="border-red" style="min-width: 100px;" />
    </div>

    <div class="row">
        <div class="col-md-2">
            <img src="@Url.Content(Model.ImageUrl)" class="img-thumbnail-circle img-circle" />
        </div>
        <div class="clearfix visible-xs visible-sm"></div>
        <div class="col-md-10">
            <dl class="dl-horizontal" style="margin-left: 10px;">
                <dt class="visible-md visible-sm visible-lg">
                    @Html.DisplayNameFor(model => model.Artist.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Artist.Name)
                </dd>

                <dt class="visible-md visible-sm visible-lg">
                    @Html.DisplayNameFor(model => model.Role)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Role)
                </dd>

                <dt class="visible-md visible-sm visible-lg">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt class="visible-md visible-sm visible-lg">
                    @Html.DisplayNameFor(model => model.BirtyDay)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.BirtyDay)
                </dd>

                <dt class="visible-md visible-sm visible-lg">
                    @Html.DisplayNameFor(model => model.Height)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Height) cm
                </dd>

                <dt class="visible-md visible-sm visible-lg">
                    @Html.DisplayNameFor(model => model.Weight)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Weight) kg
                </dd>

            </dl>
        </div>
    </div>
    
</div>
<p style="margin-top: 30px; margin-left: 20px;">
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-default btn-xs" })
    @Html.ActionLink("Back to List", "Index", "", htmlAttributes: new { @class = "btn btn-default btn-xs" })
</p>

BANGTANS/BANGTANS/Views/Member/Edit.cshtml
@model BANGTANS.Models.MemberViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>멤버 정보 수정</h2>


@using (Html.BeginForm("Edit", "Member", FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Html.DisplayFor(model => model.Artist.Name) 멤버 정보</h4>
        <hr />
        <img src="@Url.Content(Model.ImageUrl)" style="width: 150px; height: 150px;" id="img_thumbnail" name="img_thumbnail"  class="img-thumbnail-circle img-circle" />
        <div class="clearfix"></div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.StageName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StageName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StageName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 filebox preview-image">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control upload-name", @readonly = "true", @Id = "ImageUrl", @style = "max-width:180px; margin-bottom: .25em;" } })
                <label for="file">업로드</label>
                <input type="file" name="file" id="file" class="upload-hidden" />
                <div class="clearfix visible-xs"></div>
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirtyDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirtyDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirtyDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistId, "ArtistId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ArtistId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArtistId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" disabled="disabled" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "", htmlAttributes: new { @class = "btn btn-default btn-xs" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            var fileTarget = $('.filebox .upload-hidden');

            fileTarget.on('change', function () {
                if (window.FileReader) {
                    var filename = $(this)[0].files[0].name;

                    //start preview
                    var reader = new FileReader();
                    reader.onload = (function (theFile) {
                        return function (e) {
                            document.getElementById("img_thumbnail").src = e.target.result;
                        };
                    })($(this)[0].files[0]);
                    reader.readAsDataURL($(this)[0].files[0]);
                    //end preview
                } else {
                    var filename = $(this).val().split('/').pop().split('\\').pop();
                }

                //$(this).siblings('.upload-name').val(filename);
                $("input#ImageUrl").val(filename);
            });
        });
    </script>
}

BANGTANS/BANGTANS/Views/Member/Index.cshtml
@model IEnumerable<BANGTANS.Models.MemberViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>멤버 목록</h2>

<p style="text-align: right;">
    
   @Html.ActionLink("Create New", "Create", "", htmlAttributes: new { @class = "btn btn-primary" })
</p>

@foreach (var item in Model)
{
    <div class="row row-left-gray">
        <div class="col-md-2" style="min-width:120px;"><img src="@Url.Content(item.ImageUrl)" class="img-rounded img-thumbnail" /></div>
        <div class="col-md-2">@Html.DisplayFor(modelItem => item.StageName)</div>
        <div class="col-md-2">@Html.DisplayFor(modelItem => item.Role)</div>
        <div class="col-md-2">@Html.DisplayFor(modelItem => item.BirtyDay) 일생</div>
        <div class="col-md-2">@Html.DisplayFor(modelItem => item.Height) cm / @Html.DisplayFor(modelItem => item.Weight) Kg</div>
        <div class="clearfix visible-xs"></div>
        <div class="col-md-2" style="max-width:160px; padding-right:0px;">
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-default btn-xs" })
            @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-default btn-xs" })
            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-default btn-xs" })
        </div>
    </div>
}


<!--@*

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Artist.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StageName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Role)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirtyDay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Height)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Artist.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StageName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Role)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirtyDay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Height)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Weight)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
*@-->

BANGTANS/BANGTANS/Views/Member/_MemberList.cshtml
@model IEnumerable<BANGTANS.Models.MemberViewModel>

@{
    string[] borderColors = { "border-red", "border-green", "border-blue", "border-yellow" };
}

@for (int i = 0; i < Model.Count(); i++)
{
    var model = Model.ElementAt(i);

    var col = i % 4;
    if (col == 0)
    { @Html.Raw("<div class='row'>") }

    <div class="col-md-3">
        <ul class="list-unstyled">
            <li style="padding-left: 4em;">
                <img src="@Url.Content(model.ImageUrl)" class="img-thumbnail-circle img-circle" />
                <div class="clearfix"></div>
            </li>

            <li class="list-main-title">
                <div class="category-title">
                    <h4>@Url.Content(model.StageName)</h4>
                    <hr class="@borderColors[col]" style="min-width: 100px;" />
                </div>
            </li>

            <li class="list-sub-title">
                @if (model.Role != null)
                {@Url.Content(model.Role)}
            </li>

            <li style="text-align: center;">
                본명: @Url.Content(model.Name)
            </li>

            <li style="text-align: center;">
                생년월일: @Url.Content(model.BirtyDay.ToString("yyyy-MM-dd"))
            </li>

            <li style="text-align: center;">
                키: @Url.Content(model.Height.ToString()) cm
            </li>

            <li style="text-align: center; margin-bottom: 2em;">
                몸무게: @Url.Content(model.Weight.ToString()) kg
            </li>

        </ul>
    </div>
    if (col == 3)
    { @Html.Raw("</div><div class='clearfix'></div>") }
}
<div class="clearfix"></div>


<!--@*
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Artist.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StageName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Role)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirtyDay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Height)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Artist.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StageName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Role)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImageUrl)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirtyDay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Height)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Weight)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
*@-->