BANGTANS/BANGTANS/Models/AlbumViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BANGTANS.Models
{
    public class AlbumViewModel
    {
        // 앨범 아이디
        public int Id { get; set; }

        // 앨범 타이틀
        [Required]
        [Display(Name = "타이틀")]
        public string Title { get; set; }

        // 앨범 서브타이틀
        [Display(Name = "부제")]
        [DisplayFormat(NullDisplayText = "")]
        public string Subtitle { get; set; }

        // 앨범 발행일
        [Required]
        [Display(Name = "발행일")]
        [DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime ReleasedDate { get; set; }

        // 앨범 이미지 URL
        [Required]
        [DataType(DataType.Upload)]
        [Display(Name = "앨범이미지")]
        public string ImageUrl { get; set; }

        // 앨범 설명
        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "설명")]
        public string Description { get; set; }

        // 아티스트(그룹)아이디
        [Required]
        public int ArtistId { get; set; }

        // 아티스트(그룹)정보
        public virtual ArtistViewModel Artist { get; set; }

        // 수록곡목록
        public virtual ICollection<ArtistViewModel> Tracks { get; set; }
    }
}

BANGTANS/BANGTANS/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BANGTANS.Models;
using System.IO;

namespace BANGTANS.Controllers
{
    public class AlbumController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Album
        public ActionResult Index()
        {
            var albumViewModels = db.AlbumViewModels.Include(a => a.Artist);
            return View(albumViewModels.OrderByDescending(m => m.Id).ToList());
        }

        public ActionResult GetList(int id)
        {
            var albumViewModels = db.AlbumViewModels.Where(a => a.ArtistId == id).Include(a => a.Artist);
            return PartialView("_AlbumList", albumViewModels.OrderByDescending(m => m.Id).ToList());
        }

        // GET: Album/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AlbumViewModel albumViewModel = db.AlbumViewModels.Find(id);
            if (albumViewModel == null)
            {
                return HttpNotFound();
            }
            return View(albumViewModel);
        }

        // GET: Album/Create
        public ActionResult Create()
        {
            ViewBag.ArtistId = new SelectList(db.ArtistViewModels, "Id", "Name");
            return View();
        }

        // POST: Album/Create
        // 초과 게시 공격으로부터 보호하려면 바인딩하려는 특정 속성을 사용하도록 설정하십시오. 
        // 자세한 내용은 http://go.microsoft.com/fwlink/?LinkId=317598을(를) 참조하십시오.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Subtitle,ReleasedDate,ImageUrl,Description,ArtistId")] AlbumViewModel albumViewModel, HttpPostedFileBase file)
        {
            bool isSavedFile = SaveAsFile(file);
            if (isSavedFile)
            {
                albumViewModel.ImageUrl = "~/Content/Images/Album/" + file.FileName;
                
                if (ModelState.IsValid)
                {
                    db.AlbumViewModels.Add(albumViewModel);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            else
            {
                ModelState.AddModelError("ImageUrl", "Please, upload file.");
            }           

            ViewBag.ArtistId = new SelectList(db.ArtistViewModels, "Id", "Name", albumViewModel.ArtistId);
            return View(albumViewModel);
        }

        private bool SaveAsFile(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0 && IsValidExtension(file))
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/Images/Album/"), fileName);
                file.SaveAs(path);
                return  true;
            }

            return false;
        }

        private Boolean IsValidExtension(HttpPostedFileBase file)
        {
            return Path.GetExtension(file.FileName).ToLower() == ".jpg"
                || Path.GetExtension(file.FileName).ToLower() == ".png"
                || Path.GetExtension(file.FileName).ToLower() == ".gif"
                || Path.GetExtension(file.FileName).ToLower() == ".jpeg";
        }

        // GET: Album/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AlbumViewModel albumViewModel = db.AlbumViewModels.Find(id);
            if (albumViewModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArtistId = new SelectList(db.ArtistViewModels, "Id", "Name", albumViewModel.ArtistId);
            return View(albumViewModel);
        }

        // POST: Album/Edit/5
        // 초과 게시 공격으로부터 보호하려면 바인딩하려는 특정 속성을 사용하도록 설정하십시오. 
        // 자세한 내용은 http://go.microsoft.com/fwlink/?LinkId=317598을(를) 참조하십시오.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Subtitle,ReleasedDate,ImageUrl,Description,ArtistId")] AlbumViewModel albumViewModel, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                bool isFileChanged = SaveAsFile(file);

                db.Entry(albumViewModel).State = EntityState.Modified;
                if(isFileChanged) albumViewModel.ImageUrl = "~/Content/Images/Album/" + file.FileName;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ArtistId = new SelectList(db.ArtistViewModels, "Id", "Name", albumViewModel.ArtistId);
            return View(albumViewModel);
        }

        // GET: Album/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AlbumViewModel albumViewModel = db.AlbumViewModels.Find(id);
            if (albumViewModel == null)
            {
                return HttpNotFound();
            }
            return View(albumViewModel);
        }

        // POST: Album/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AlbumViewModel albumViewModel = db.AlbumViewModels.Find(id);
            db.AlbumViewModels.Remove(albumViewModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Video()
        {
            ViewBag.VideoSources = new List<string>()
            {
                "https://youtu.be/MBdVXkSdhwU", "https://youtu.be/ALj5MKjy2BU", "https://youtu.be/BVwAVbKYYeM"
                , "https://youtu.be/hmE9f-TEutc", "https://youtu.be/NMdTd9e-LEI", "https://youtu.be/9DwzBICPhdM"
                , "https://youtu.be/GZjt_sA2eso", "https://youtu.be/bagj78IQ3l0", "https://youtu.be/m8MfJg68oCs"
            };

            ViewBag.VideoTitles = new List<string>()
            {
                "DNA", "불타오르네", "DOPE: 쩔어", "피 땀 눈물", "I NEED YOU", "Not Today", "Save ME", "Danger", "상남자"
            };

            return View();
        }

        [ActionName("aspnet-mvc-helper")]
        public ActionResult VideoList()
        {
            ViewBag.VideoSources = new List<string>()
            {
                "https://youtu.be/MBdVXkSdhwU", "https://youtu.be/ALj5MKjy2BU", "https://youtu.be/BVwAVbKYYeM"
                , "https://youtu.be/hmE9f-TEutc", "https://youtu.be/NMdTd9e-LEI", "https://youtu.be/9DwzBICPhdM"
                , "https://youtu.be/GZjt_sA2eso", "https://youtu.be/bagj78IQ3l0", "https://youtu.be/m8MfJg68oCs"
            };

            ViewBag.VideoTitles = new List<string>()
            {
                "DNA", "불타오르네", "DOPE: 쩔어", "피 땀 눈물", "I NEED YOU", "Not Today", "Save ME", "Danger", "상남자"
            }; 

            return View("aspnet-mvc-helper");
        }

        [ActionName("fallback-video")]
        public ActionResult FallbackVideo()
        {
            ViewBag.VideoSources = new List<string>()
            {
                "https://youtu.be/MBdVXkSdhwU", "https://youtu.be/ALj5MKjy2BU", "https://youtu.be/BVwAVbKYYeM"
                , "https://youtu.be/hmE9f-TEutc", "https://youtu.be/NMdTd9e-LEI", "https://youtu.be/9DwzBICPhdM"
                , "https://youtu.be/GZjt_sA2eso", "https://youtu.be/bagj78IQ3l0", "https://youtu.be/m8MfJg68oCs"
            };

            ViewBag.VideoTitles = new List<string>()
            {
                "DNA", "불타오르네", "DOPE: 쩔어", "피 땀 눈물", "I NEED YOU", "Not Today", "Save ME", "Danger", "상남자"
            };

            return View("fallback-video");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BANGTANS/BANGTANS/Views/Album/Create.cshtml
@model BANGTANS.Models.AlbumViewModel

@{
    ViewBag.Title = "Create";
}


<h2>앨범 등록</h2>

@using (Html.BeginForm("Create", "Album", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>앨범 정보</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*@Html.HiddenFor(model => model.ImageUrl)*@

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subtitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subtitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subtitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleasedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleasedDate, new { htmlAttributes = new { @class = "form-control datefield input-group input-append date", @type = "date", @Id = "ReleasedDate" } })
                @Html.ValidationMessageFor(model => model.ReleasedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10 filebox preview-image">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control upload-name", @readonly = "true", @Id = "ImageUrl", @style = "max-width: 210px; margin-bottom: .25em;" } })
                <label for="file">업로드</label>
                <input type="file" name="file" id="file" class="upload-hidden"/>
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>
        

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistId, "ArtistId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ArtistId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArtistId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" disabled="disabled" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "", htmlAttributes: new { @class = "btn btn-default btn-xs" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script>
        $(document).ready(function () {
            var fileTarget = $('.filebox .upload-hidden');
           
            fileTarget.on('change', function () {
                if (window.FileReader) {
                    var filename = $(this)[0].files[0].name;
                } else {
                    var filename = $(this).val().split('/').pop().split('\\').pop();
                }

                //$(this).siblings('.upload-name').val(filename);
                $("input#ImageUrl").val(filename);
            });
        });
    </script>
}

BANGTANS/BANGTANS/Views/Album/Delete.cshtml
@model BANGTANS.Models.AlbumViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>정보 삭제</h2>

<h3>앨범 정보</h3>
<div>
    <h4>(삭제한 앨범 정보는 복구할 수 없으니, 확인 후 삭제하세요.)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artist.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subtitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subtitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleasedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleasedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Url.Content(Model.ImageUrl.Substring(Model.ImageUrl.LastIndexOf('/') + 1))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Back to List", "Index", "", htmlAttributes: new { @class = "btn btn-default btn-xs" })
            <span>&nbsp;&nbsp;&nbsp;</span>
            <input type="submit" value="Delete" class="btn btn-primary" disabled="disabled" />
        </div>
    }
</div>

BANGTANS/BANGTANS/Views/Album/Details.cshtml
@model BANGTANS.Models.AlbumViewModel

@{
    ViewBag.Title = "Details";
}

<h2> 앨범 상세 정보</h2>

<div>
    @Html.Partial("_DetailForm")
</div>

<p style="margin-top: 30px; margin-left: 20px;">
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-default btn-xs" })
    @Html.ActionLink("Back to List", "Index", "", htmlAttributes: new { @class = "btn btn-default btn-xs" })
</p>

BANGTANS/BANGTANS/Views/Album/Edit.cshtml
@model BANGTANS.Models.AlbumViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>수정</h2>


@using (Html.BeginForm("Edit", "Album", FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>앨범 내용</h4>
        <hr />
        <div class="img-thumbnail-circle img-innerborder img-circle"><img src="@Url.Content(Model.ImageUrl)" style="width: 150px; height: 150px;" id="img_thumbnail" name="img_thumbnail" /></div>
        <div class="clearfix"></div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subtitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subtitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subtitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleasedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleasedDate, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.ReleasedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 filebox preview-image">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control upload-name", @readonly = "true", @Id = "ImageUrl", @style = "max-width:180px; margin-bottom: .25em;" } })
                <label for="file">업로드</label>
                <input type="file" name="file" id="file" class="upload-hidden" />
                <div class="clearfix visible-xs"></div>
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistId, "ArtistId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ArtistId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArtistId, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" disabled="disabled" />
            </div>
        </div>
    </div>
}


    <div>
        @Html.ActionLink("Back to List", "Index", "", htmlAttributes: new { @class = "btn btn-default btn-xs" })
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")

        <script>
                $(document).ready(function () {
                    var fileTarget = $('.filebox .upload-hidden');

                    fileTarget.on('change', function () {
                        if (window.FileReader) {
                            var filename = $(this)[0].files[0].name;

                            //start preview
                            var reader = new FileReader();
                            reader.onload = (function (theFile) {
                                return function (e) {
                                    document.getElementById("img_thumbnail").src = e.target.result;
                                };
                            })($(this)[0].files[0]);
                            reader.readAsDataURL($(this)[0].files[0]);
                            //end preview

                        } else {
                            var filename = $(this).val().split('/').pop().split('\\').pop();
                        }

                        $("input#ImageUrl").val(filename);
                    });
                });
        </script>
    }

BANGTANS/BANGTANS/Views/Album/Index.cshtml
@model IEnumerable<BANGTANS.Models.AlbumViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>앨범 목록</h2>

<p style="text-align: right;">
    @Html.ActionLink("Create New", "Create", "", htmlAttributes: new { @class = "btn btn-primary" })
</p>

<!--
@*<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#firstTab">View All</a></li>
    <li><a data-toggle="tab" href="#secondTab">Add New</a></li>
</ul>

<div class="tab-content">
    <div id="firstTab" class="tab-pane fade in active">@Html.Action("Index", "Album")</div>
    <div id="secondTab" class="tab-pane fade in">@Html.Action("Create", "Album")</div>
</div>
*@
-->
<!--
@*
<div class="row" style="padding:10px 0px; margin: 2px;">
    <div class="col-md-2" style="min-width:100px;">@Html.DisplayNameFor(model => model.Artist.Name)</div>
    <div class="col-md-1">@Html.DisplayNameFor(model => model.ReleasedDate)</div>
    <div class="clearfix visible-xs"></div>
    <div class="col-xs-0 col-md-7">@Html.DisplayNameFor(model => model.Subtitle)（@Html.DisplayNameFor(model => model.Artist.Name)）</div>
    <div class="col-md-2" style="min-width:200px;"></div>
</div>
    
*@
-->
@foreach (var item in Model)
{
    <div class="row" style="border:1px solid gray; border-left:6px solid gray; border-radius:5px; padding:10px 0px; margin: 2px;">
        <div class="col-md-2" style="min-width:120px;"><img src="@Url.Content(item.ImageUrl)" class = "img-thumbnail" /></div>
        <!--@*<div class="col-md-1">@Html.DisplayFor(modelItem => item.ReleasedDate)</div>*@-->
        <div class="col-md-2">@Html.DisplayFor(modelItem => item.Title)</div>
        <div class="clearfix visible-xs"></div>
        <div class="col-xs-0 col-md-6" style="overflow:hidden; white-space: nowrap; text-overflow:ellipsis;">@Html.DisplayFor(modelItem => item.Description)</div>
        <div class="col-md-2" style="max-width:160px; padding-right:0px;">
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-default btn-xs" })
            @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-default btn-xs" })
            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-default btn-xs" })
        </div>
    </div>
}

BANGTANS/BANGTANS/Views/Album/_EditForm.cshtml
@model BANGTANS.Models.AlbumViewModel

@using (Html.BeginForm("Edit", "Album", FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data", id = "editForm" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>앨범 내용</h4>
        <hr />
        <div class="img-thumbnail-circle img-innerborder img-circle"><img src="@Url.Content(Model.ImageUrl)" style="width: 150px; height: 150px;" id="img_thumbnail" name="img_thumbnail" /></div>
        <div class="clearfix"></div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subtitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subtitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subtitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleasedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleasedDate, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.ReleasedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 filebox preview-image">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control upload-name", @readonly = "true", @Id = "ImageUrl", @style = "max-width:180px; margin-bottom: .25em;" } })
                <label for="file">업로드</label>
                <input type="file" name="file" id="file" class="upload-hidden" />
                <div class="clearfix visible-xs"></div>
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArtistId, "ArtistId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ArtistId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArtistId, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "", htmlAttributes: new { @class = "btn btn-default btn-xs" })
</div>

BANGTANS/BANGTANS/Views/Album/_EditSuccess.cshtml
@model BANGTANS.Models.AlbumViewModel

<h4>수정 앨범 정보</h4>

<div>
    @Html.Partial("_DetailForm")
</div>


<div class="clearfix visible-lg visible-md visible-sm visible-xs"></div>
<div class="visible-lg visible-md" style="min-height: 20px"></div>

@*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-primary" })*@